// biome-ignore-all lint: generated bundle
// biome-ignore-all format: generated bundle
/**
 * @generated by skills/tourkit/build/build-recorder.mjs — DO NOT EDIT.
 *
 * Source: skills/tourkit/build/recorder-entry.js
 * Bundled from @tourkit/core/dom so the recorder and the player agree on what a target is.
 * Rebuild: node skills/tourkit/build/build-recorder.mjs
 */
(() => {
// packages/core/src/dom/fingerprint.ts
function normalize(value) {
  const trimmed = value?.trim().replace(/\s+/g, " ");
  return trimmed ? trimmed.slice(0, 120) : undefined;
}
function positionOf(element) {
  const parent = element.parentElement;
  if (!parent)
    return;
  const siblings = [...parent.children].filter((child) => child.tagName === element.tagName);
  if (siblings.length < 2)
    return;
  return siblings.indexOf(element) + 1;
}
function nearestHeading(element) {
  let current = element;
  while (current) {
    let sibling = current.previousElementSibling;
    while (sibling) {
      if (/^H[1-6]$/.test(sibling.tagName))
        return normalize(sibling.textContent);
      const nested = sibling.querySelector("h1, h2, h3, h4, h5, h6");
      if (nested)
        return normalize(nested.textContent);
      sibling = sibling.previousElementSibling;
    }
    current = current.parentElement;
    const label = current?.getAttribute("aria-label");
    if (label)
      return normalize(label);
  }
  return;
}
function buildFingerprint(element) {
  const label = normalize(element.getAttribute("data-tour-label")) ?? normalize(element.getAttribute("aria-label"));
  return {
    tag: element.tagName.toLowerCase(),
    ...normalize(element.textContent) ? { text: normalize(element.textContent) } : {},
    ...element.getAttribute("role") ? { role: element.getAttribute("role") } : {},
    ...label ? { label } : {},
    ...nearestHeading(element) ? { near: nearestHeading(element) } : {},
    ...positionOf(element) ? { index: positionOf(element) } : {}
  };
}

// packages/core/src/dom/selector.ts
var STABLE_ID = /^[a-zA-Z][\w-]*$/;
function isUnique(selector, root) {
  try {
    return root.querySelectorAll(selector).length === 1;
  } catch {
    return false;
  }
}
var SEMANTIC_CLASS = /^[a-zA-Z][a-zA-Z-]{1,38}$/;
function stableClass(element) {
  return Array.from(element.classList).find((name) => SEMANTIC_CLASS.test(name)) ?? null;
}
function segment(element) {
  const tag = element.tagName.toLowerCase();
  const parent = element.parentElement;
  if (!parent)
    return tag;
  const siblings = Array.from(parent.children).filter((child) => child.tagName === element.tagName);
  if (siblings.length === 1)
    return tag;
  return `${tag}:nth-of-type(${siblings.indexOf(element) + 1})`;
}
function cssPath(element, root = document) {
  const testId = element.getAttribute("data-testid");
  if (testId && isUnique(`[data-testid="${testId}"]`, root))
    return `[data-testid="${testId}"]`;
  if (element.id && STABLE_ID.test(element.id) && isUnique(`#${element.id}`, root)) {
    return `#${element.id}`;
  }
  const parts = [];
  let current = element;
  while (current && current !== root.documentElement && parts.length < 6) {
    const className = stableClass(current);
    const own = className ? `${segment(current)}.${className}` : segment(current);
    parts.unshift(own);
    const candidate = parts.join(" > ");
    if (isUnique(candidate, root))
      return candidate;
    current = current.parentElement;
  }
  return parts.join(" > ");
}
function textOf(element) {
  const text = element.textContent?.trim().replace(/\s+/g, " ");
  if (!text)
    return;
  return text.slice(0, 120);
}
function registeredId(element, registry) {
  if (!registry)
    return null;
  let bestId = null;
  let bestNode = null;
  for (const [id, node] of registry) {
    if (node === element)
      return id;
    if (!node.contains(element))
      continue;
    if (bestNode === null || bestNode.contains(node)) {
      bestId = id;
      bestNode = node;
    }
  }
  return bestId;
}
function describeElement(element, route = "", registry) {
  const tourId = element.getAttribute("data-tour-id") ?? registeredId(element, registry);
  const label = element.getAttribute("data-tour-label") ?? element.getAttribute("aria-label");
  const role = element.getAttribute("role") ?? undefined;
  const text = textOf(element);
  return {
    target: tourId ?? cssPath(element),
    registered: Boolean(tourId),
    tag: element.tagName.toLowerCase(),
    ...label ? { label } : {},
    ...role ? { role } : {},
    ...text ? { text } : {},
    ...route ? { route } : {},
    fingerprint: buildFingerprint(element)
  };
}
// skills/tourkit/build/recorder-entry.js
var PANEL_Z = 2147483000;
var MARKER = "data-tourkit-recorder";
var STATUS_INTERVAL_MS = 2000;
function serverOrigin() {
  const current = document.currentScript;
  if (current?.src) {
    try {
      return new URL(current.src).origin;
    } catch {}
  }
  const tag = document.querySelector('script[src*="/recorder.js"]');
  if (tag) {
    try {
      return new URL(tag.src, window.location.href).origin;
    } catch {}
  }
  return "http://127.0.0.1:5178";
}
var ORIGIN = serverOrigin();
function element(tag, style, attributes) {
  const node = document.createElement(tag);
  if (style)
    node.style.cssText = style;
  if (attributes)
    for (const [name, value] of Object.entries(attributes))
      node.setAttribute(name, value);
  return node;
}
function button(label, attribute) {
  const node = element("button", "font:inherit;padding:4px 10px;border-radius:6px;border:1px solid #374151;background:#1F2937;color:inherit;cursor:pointer;");
  node.type = "button";
  node.textContent = label;
  node.setAttribute(attribute, "");
  return node;
}
function start() {
  if (document.querySelector(`[${MARKER}]`))
    return;
  const name = window.__TOURKIT_RECORDING_NAME__ || "recorded";
  let recording = false;
  let captured = [];
  let sent = "idle";
  let outDir = null;
  const panel = element("div", `position:fixed;right:16px;bottom:16px;z-index:${PANEL_Z};display:flex;flex-direction:column;gap:8px;` + "padding:12px;border-radius:12px;background:#111827;color:#F9FAFB;" + "font:13px system-ui,sans-serif;box-shadow:0 6px 24px rgba(0,0,0,0.35);max-width:320px;", { [MARKER]: "", "data-tourkit-recording": "false" });
  const heading = element("strong");
  heading.textContent = "tourkit recorder";
  const count = element("span", null, { "data-tourkit-recorder-count": "" });
  const status = element("span", null, { "data-tourkit-recorder-status": "" });
  const target = element("span", "opacity:0.7;", { "data-tourkit-recorder-outdir": "" });
  const row = element("div", "display:flex;gap:6px;");
  const toggle = button("Record", "data-tourkit-recorder-toggle");
  const undo = button("Undo", "data-tourkit-recorder-undo");
  const save = button("Save", "data-tourkit-recorder-finish");
  row.append(toggle, undo, save);
  const list = element("ol", "margin:0;padding-left:18px;max-width:280px;", {
    "data-tourkit-recorder-list": ""
  });
  panel.append(heading, count, status, target, row, list);
  function render() {
    panel.setAttribute("data-tourkit-recording", recording ? "true" : "false");
    count.textContent = `${captured.length} step${captured.length === 1 ? "" : "s"}`;
    status.textContent = sent;
    target.textContent = outDir ? `→ ${outDir}` : "";
    toggle.textContent = recording ? "Stop" : "Record";
    list.replaceChildren(...captured.map((step) => {
      const item = element("li", "overflow-wrap:anywhere;");
      item.textContent = step.label || step.text || step.target;
      return item;
    }));
  }
  function onClick(event) {
    if (!recording)
      return;
    const node = event.target;
    if (!(node instanceof Element))
      return;
    if (node.closest(`[${MARKER}]`))
      return;
    event.preventDefault();
    event.stopPropagation();
    captured.push(describeElement(node, window.location.pathname));
    render();
  }
  document.addEventListener("click", onClick, true);
  toggle.addEventListener("click", () => {
    sent = "idle";
    recording = !recording;
    render();
  });
  undo.addEventListener("click", () => {
    captured = captured.slice(0, -1);
    render();
  });
  save.addEventListener("click", async () => {
    recording = false;
    sent = "sending";
    render();
    try {
      const response = await fetch(`${ORIGIN}/record`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ name, createdAt: Date.now(), steps: captured })
      });
      sent = response.ok ? "sent" : "failed";
    } catch {
      sent = "failed";
    }
    render();
  });
  let online = false;
  async function ping() {
    try {
      const response = await fetch(`${ORIGIN}/status`, { method: "GET" });
      if (!response.ok)
        throw new Error("offline");
      const body = await response.json();
      online = Boolean(body?.ok);
      outDir = body?.outDir || null;
    } catch {
      online = false;
      outDir = null;
    }
    if (online && !panel.isConnected)
      document.body.appendChild(panel);
    if (!online && panel.isConnected)
      panel.remove();
    if (panel.isConnected)
      render();
  }
  ping();
  setInterval(() => void ping(), STATUS_INTERVAL_MS);
}
if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", start, { once: true });
} else {
  start();
}
})();
