import { expect, test } from "@playwright/test";

test("a tour generated by the recorder runs untouched", async ({ page }) => {
  await page.goto("/");
  await page.evaluate(() => localStorage.clear());
  await page.reload();

  await page.click("#launch-recorded-walkthrough");

  const titles = ["My rides", "Ride options", "Cancel ride", "Hero button", "Inside modal"];
  for (const title of titles) {
    await expect(page.locator('[data-tourkit="card"]')).toContainText(title);
    await page.click('[data-tourkit="next"]');
    await page.waitForTimeout(120);
  }

  await expect(page.locator('[data-tourkit="card"]')).toContainText("That is the tour");
  await expect(page.locator('[data-tourkit="card-wrap"]')).toHaveAttribute(
    "data-tourkit-placement",
    "center",
  );

  await page.click('[data-tourkit="next"]');
  await expect(page.locator('[data-tourkit="root"]')).toHaveCount(0);
});

test("the recorded selector targets resolve to the real elements", async ({ page }) => {
  await page.goto("/");
  await page.evaluate(() => localStorage.clear());
  await page.reload();

  await page.click("#launch-recorded-walkthrough");
  for (let step = 0; step < 3; step += 1) {
    await page.click('[data-tourkit="next"]');
    await page.waitForTimeout(150);
  }

  await expect(page.locator('[data-tourkit="card"]')).toContainText("Hero button");

  const target = await page.locator("#hero").boundingBox();
  const hole = await page.evaluate(() => {
    const clip = getComputedStyle(
      document.querySelector('[data-tourkit="backdrop"]') as Element,
    ).clipPath;
    const data = clip.slice(clip.indexOf('"') + 1, clip.lastIndexOf('"'));
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute("d", data.slice(data.indexOf("Z") + 1));
    svg.appendChild(path);
    document.body.appendChild(svg);
    const box = path.getBBox();
    svg.remove();
    return { x: box.x, y: box.y };
  });

  expect(Math.abs(hole.x - ((target?.x ?? 0) - 4))).toBeLessThan(2);
});
